package rift_extractor.classgen.classes;
import org.imathrowback.datparser.CObject;
import static rift_extractor.classgen.ClassUtils.*;
import rift_extractor.classgen.ClassUtils;

/** 11514 **/
@com.thoughtworks.xstream.annotations.XStreamAlias("_11514")
public class _11514 
{
	public _11514(){}
	public java.lang.Float unk0;
	public java.lang.Float unk1;
	public java.lang.Float unk2;
	public java.lang.Float unk3;
	public java.lang.Float unk4;
	public java.lang.Float unk5;
	Object unk6;
	Object unk7;
	public java.util.List<java.lang.Long> unk8;
	Object unk9;
	Object unk10;
	Object unk11;
	public java.lang.Float unk12;
	Object unk13;
	Object unk14;
	Object unk15;
	Object unk16;
	public java.lang.Long unk17;
	public java.lang.Long unk18;
	public java.lang.Long unk19;
	Object unk20;
	Object unk21;
	Object unk22;
	Object unk23;
	Object unk24;
	Object unk25;
	Object unk26;
	Object unk27;
	Object unk28;
	Object unk29;
	Object unk30;
	Object unk31;
	public java.lang.Long unk32;
	Object unk33;
	Object unk34;
	Object unk35;
	public java.lang.Long unk36;
	Object unk37;
	public java.lang.Boolean unk38;
	Object unk39;
	public java.lang.Boolean unk40;
	Object unk41;
	Object unk42;
	public java.lang.Boolean unk43;
	public java.lang.Float unk44;
	public java.lang.Float unk45;
	public ID unk46;
	public java.lang.String unk47;
	public java.lang.Float unk48;
	public java.lang.Float unk49;
	public java.lang.Float unk50;
	public java.lang.Float unk51;
	Object unk52;
	public java.lang.Float unk53;
	public java.lang.Float unk54;
	public java.lang.Float unk55;
	public java.lang.Float unk56;
	public java.lang.Boolean unk57;
	Object unk58;
	Object unk59;
	public java.lang.Long unk60;
	public java.lang.Float unk61;
	public java.lang.Float unk62;

	public void parse(CObject obj)
	{
		ClassUtils.assertType(obj, 11514);

		unk0 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 0);
		unk1 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 1);
		unk2 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 2);
		unk3 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 3);
		unk4 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 4);
		unk5 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 5);
		unk6 = ClassUtils.getFieldMember(Object.class,obj, 6);
		unk7 = ClassUtils.getFieldMember(Object.class,obj, 7);
		unk8 = ClassUtils.list(java.lang.Long.class,obj,8);
		unk9 = ClassUtils.getFieldMember(Object.class,obj, 9);
		unk10 = ClassUtils.getFieldMember(Object.class,obj, 10);
		unk11 = ClassUtils.getFieldMember(Object.class,obj, 11);
		unk12 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 12);
		unk13 = ClassUtils.getFieldMember(Object.class,obj, 13);
		unk14 = ClassUtils.getFieldMember(Object.class,obj, 14);
		unk15 = ClassUtils.getFieldMember(Object.class,obj, 15);
		unk16 = ClassUtils.getFieldMember(Object.class,obj, 16);
		unk17 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 17);
		unk18 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 18);
		unk19 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 19);
		unk20 = ClassUtils.getFieldMember(Object.class,obj, 20);
		unk21 = ClassUtils.getFieldMember(Object.class,obj, 21);
		unk22 = ClassUtils.getFieldMember(Object.class,obj, 22);
		unk23 = ClassUtils.getFieldMember(Object.class,obj, 23);
		unk24 = ClassUtils.getFieldMember(Object.class,obj, 24);
		unk25 = ClassUtils.getFieldMember(Object.class,obj, 25);
		unk26 = ClassUtils.getFieldMember(Object.class,obj, 26);
		unk27 = ClassUtils.getFieldMember(Object.class,obj, 27);
		unk28 = ClassUtils.getFieldMember(Object.class,obj, 28);
		unk29 = ClassUtils.getFieldMember(Object.class,obj, 29);
		unk30 = ClassUtils.getFieldMember(Object.class,obj, 30);
		unk31 = ClassUtils.getFieldMember(Object.class,obj, 31);
		unk32 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 32);
		unk33 = ClassUtils.getFieldMember(Object.class,obj, 33);
		unk34 = ClassUtils.getFieldMember(Object.class,obj, 34);
		unk35 = ClassUtils.getFieldMember(Object.class,obj, 35);
		unk36 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 36);
		unk37 = ClassUtils.getFieldMember(Object.class,obj, 37);
		unk38 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 38);
		unk39 = ClassUtils.getFieldMember(Object.class,obj, 39);
		unk40 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 40);
		unk41 = ClassUtils.getFieldMember(Object.class,obj, 41);
		unk42 = ClassUtils.getFieldMember(Object.class,obj, 42);
		unk43 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 43);
		unk44 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 44);
		unk45 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 45);
		unk46 = ClassUtils.getFieldMember(ID.class,obj, 46);
		unk47 = ClassUtils.getFieldMember(java.lang.String.class,obj, 47);
		unk48 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 48);
		unk49 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 49);
		unk50 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 50);
		unk51 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 51);
		unk52 = ClassUtils.getFieldMember(Object.class,obj, 52);
		unk53 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 53);
		unk54 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 54);
		unk55 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 55);
		unk56 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 56);
		unk57 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 57);
		unk58 = ClassUtils.getFieldMember(Object.class,obj, 58);
		unk59 = ClassUtils.getFieldMember(Object.class,obj, 59);
		unk60 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 60);
		unk61 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 61);
		unk62 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 62);
	}
}
