package rift_extractor.classgen.classes;
import org.imathrowback.datparser.CObject;
import static rift_extractor.classgen.ClassUtils.*;
import rift_extractor.classgen.ClassUtils;

/** 11524 **/
@com.thoughtworks.xstream.annotations.XStreamAlias("_11524")
public class _11524 
{
	public _11524(){}
	java.lang.Float unk0;
	java.lang.Float unk1;
	java.lang.Float unk2;
	java.lang.Float unk3;
	java.lang.Float unk4;
	java.lang.Float unk5;
	Object unk6;
	Object unk7;
	Object unk8;
	Object unk9;
	Object unk10;
	Object unk11;
	java.lang.Float unk12;
	Object unk13;
	Object unk14;
	Object unk15;
	Object unk16;
	Object unk17;
	Object unk18;
	Object unk19;
	Object unk20;
	Object unk21;
	Object unk22;
	Object unk23;
	Object unk24;
	java.lang.Long unk25;
	java.lang.Float unk26;
	Object unk27;
	Object unk28;
	java.lang.Float unk29;
	java.lang.Float unk30;
	java.lang.Float unk31;
	java.lang.Float unk32;
	java.lang.Float unk33;
	java.lang.Float unk34;
	java.lang.Float unk35;
	java.lang.Float unk36;
	java.lang.Float unk37;
	java.lang.Float unk38;
	java.lang.Float unk39;
	Object unk40;
	Object unk41;
	Object unk42;
	java.lang.Float unk43;
	java.lang.Float unk44;
	Object unk45;
	java.lang.Float unk46;
	java.lang.Float unk47;
	java.lang.Float unk48;
	java.lang.Float unk49;
	Object unk50;
	Object unk51;
	java.lang.Float unk52;
	java.lang.Float unk53;
	java.lang.Float unk54;
	java.lang.Float unk55;
	Object unk56;
	Object unk57;
	Object unk58;
	Object unk59;
	java.lang.Float unk60;
	java.lang.Float unk61;
	Object unk62;
	java.lang.Float unk63;
	Object unk64;
	Object unk65;
	Object unk66;
	Object unk67;
	Object unk68;
	Object unk69;
	Object unk70;
	java.lang.Float unk71;
	java.lang.Float unk72;
	java.lang.Float unk73;
	java.lang.Float unk74;
	java.lang.Float unk75;
	java.lang.Float unk76;
	java.lang.Float unk77;
	java.lang.Float unk78;
	Object unk79;
	java.lang.Float unk80;
	java.lang.Float unk81;
	java.lang.Float unk82;
	java.lang.Float unk83;
	java.lang.Float unk84;
	java.lang.Float unk85;
	java.lang.Float unk86;
	Object unk87;
	java.lang.Float unk88;
	java.lang.Float unk89;
	java.lang.Float unk90;
	java.lang.Float unk91;
	java.lang.Float unk92;
	java.lang.Float unk93;
	java.lang.Float unk94;

	public void parse(CObject obj)
	{
		ClassUtils.assertType(obj, 11524);

		unk0 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 0);
		unk1 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 1);
		unk2 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 2);
		unk3 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 3);
		unk4 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 4);
		unk5 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 5);
		unk6 = ClassUtils.getFieldMember(Object.class,obj, 6);
		unk7 = ClassUtils.getFieldMember(Object.class,obj, 7);
		unk8 = ClassUtils.getFieldMember(Object.class,obj, 8);
		unk9 = ClassUtils.getFieldMember(Object.class,obj, 9);
		unk10 = ClassUtils.getFieldMember(Object.class,obj, 10);
		unk11 = ClassUtils.getFieldMember(Object.class,obj, 11);
		unk12 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 12);
		unk13 = ClassUtils.getFieldMember(Object.class,obj, 13);
		unk14 = ClassUtils.getFieldMember(Object.class,obj, 14);
		unk15 = ClassUtils.getFieldMember(Object.class,obj, 15);
		unk16 = ClassUtils.getFieldMember(Object.class,obj, 16);
		unk17 = ClassUtils.getFieldMember(Object.class,obj, 17);
		unk18 = ClassUtils.getFieldMember(Object.class,obj, 18);
		unk19 = ClassUtils.getFieldMember(Object.class,obj, 19);
		unk20 = ClassUtils.getFieldMember(Object.class,obj, 20);
		unk21 = ClassUtils.getFieldMember(Object.class,obj, 21);
		unk22 = ClassUtils.getFieldMember(Object.class,obj, 22);
		unk23 = ClassUtils.getFieldMember(Object.class,obj, 23);
		unk24 = ClassUtils.getFieldMember(Object.class,obj, 24);
		unk25 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 25);
		unk26 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 26);
		unk27 = ClassUtils.getFieldMember(Object.class,obj, 27);
		unk28 = ClassUtils.getFieldMember(Object.class,obj, 28);
		unk29 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 29);
		unk30 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 30);
		unk31 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 31);
		unk32 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 32);
		unk33 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 33);
		unk34 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 34);
		unk35 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 35);
		unk36 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 36);
		unk37 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 37);
		unk38 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 38);
		unk39 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 39);
		unk40 = ClassUtils.getFieldMember(Object.class,obj, 40);
		unk41 = ClassUtils.getFieldMember(Object.class,obj, 41);
		unk42 = ClassUtils.getFieldMember(Object.class,obj, 42);
		unk43 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 43);
		unk44 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 44);
		unk45 = ClassUtils.getFieldMember(Object.class,obj, 45);
		unk46 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 46);
		unk47 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 47);
		unk48 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 48);
		unk49 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 49);
		unk50 = ClassUtils.getFieldMember(Object.class,obj, 50);
		unk51 = ClassUtils.getFieldMember(Object.class,obj, 51);
		unk52 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 52);
		unk53 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 53);
		unk54 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 54);
		unk55 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 55);
		unk56 = ClassUtils.getFieldMember(Object.class,obj, 56);
		unk57 = ClassUtils.getFieldMember(Object.class,obj, 57);
		unk58 = ClassUtils.getFieldMember(Object.class,obj, 58);
		unk59 = ClassUtils.getFieldMember(Object.class,obj, 59);
		unk60 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 60);
		unk61 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 61);
		unk62 = ClassUtils.getFieldMember(Object.class,obj, 62);
		unk63 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 63);
		unk64 = ClassUtils.getFieldMember(Object.class,obj, 64);
		unk65 = ClassUtils.getFieldMember(Object.class,obj, 65);
		unk66 = ClassUtils.getFieldMember(Object.class,obj, 66);
		unk67 = ClassUtils.getFieldMember(Object.class,obj, 67);
		unk68 = ClassUtils.getFieldMember(Object.class,obj, 68);
		unk69 = ClassUtils.getFieldMember(Object.class,obj, 69);
		unk70 = ClassUtils.getFieldMember(Object.class,obj, 70);
		unk71 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 71);
		unk72 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 72);
		unk73 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 73);
		unk74 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 74);
		unk75 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 75);
		unk76 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 76);
		unk77 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 77);
		unk78 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 78);
		unk79 = ClassUtils.getFieldMember(Object.class,obj, 79);
		unk80 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 80);
		unk81 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 81);
		unk82 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 82);
		unk83 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 83);
		unk84 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 84);
		unk85 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 85);
		unk86 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 86);
		unk87 = ClassUtils.getFieldMember(Object.class,obj, 87);
		unk88 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 88);
		unk89 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 89);
		unk90 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 90);
		unk91 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 91);
		unk92 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 92);
		unk93 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 93);
		unk94 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 94);
	}
}
