package rift_extractor.classgen.classes;
import org.imathrowback.datparser.CObject;
import static rift_extractor.classgen.ClassUtils.*;
import rift_extractor.classgen.ClassUtils;

/** 1859 **/
@com.thoughtworks.xstream.annotations.XStreamAlias("_1859")
public class _1859 
{
	public _1859(){}
	Object unk0;
	Object unk1;
	Object unk2;
	Object unk3;
	Object unk4;
	Object unk5;
	Object unk6;
	Object unk7;
	Object unk8;
	Object unk9;
	public java.lang.Long unk10;
	public java.util.List<_1865> unk11;
	Object unk12;
	public java.util.List<java.lang.Long> unk13;
	Object unk14;
	public java.util.List<_1868> unk15;
	Object unk16;
	Object unk17;
	Object unk18;
	Object unk19;
	Object unk20;
	public java.util.List<_3230> unk21;
	public java.lang.Float unk22;
	Object unk23;
	public java.util.List<java.lang.Long> unk24;
	public java.util.List<java.lang.Long> unk25;
	public java.lang.Float unk26;
	public java.lang.Boolean unk27;
	Object unk28;
	public java.lang.Boolean unk29;
	Object unk30;
	public java.lang.Float unk31;
	public java.util.List<java.lang.Long> unk32;
	public java.lang.Float unk33;
	public java.lang.Float unk34;
	Object unk35;
	Object unk36;
	Object unk37;
	Object unk38;
	Object unk39;
	public java.util.List<java.lang.Long> unk40;
	Object unk41;
	public java.util.List<java.lang.Long> unk42;
	Object unk43;
	Object unk44;
	public java.lang.Float unk45;
	public java.util.List<java.lang.Long> unk46;
	public java.util.List<java.lang.Long> unk47;
	Object unk48;
	Object unk49;
	Object unk50;
	Object unk51;
	Object unk52;
	Object unk53;
	Object unk54;
	Object unk55;
	Object unk56;
	Object unk57;
	Object unk58;
	Object unk59;
	public java.lang.Float unk60;
	Object unk61;
	public java.util.List<java.lang.Long> unk62;
	public java.lang.Float unk63;
	public java.lang.Float unk64;
	public java.util.List<java.lang.Long> unk65;
	Object unk66;
	Object unk67;
	Object unk68;
	public java.lang.Long unk69;
	Object unk70;
	Object unk71;
	Object unk72;
	public java.lang.Float unk73;
	public java.util.List<java.lang.Long> unk74;
	Object unk75;
	Object unk76;
	Object unk77;
	public java.lang.Float unk78;
	public java.lang.Float unk79;
	public java.util.List<java.lang.Long> unk80;
	public java.lang.Boolean unk81;
	Object unk82;
	Object unk83;
	Object unk84;
	public java.util.List<java.lang.Long> unk85;
	Object unk86;
	public java.lang.Float unk87;

	public void parse(CObject obj)
	{
		ClassUtils.assertType(obj, 1859);

		unk0 = ClassUtils.getFieldMember(Object.class,obj, 0);
		unk1 = ClassUtils.getFieldMember(Object.class,obj, 1);
		unk2 = ClassUtils.getFieldMember(Object.class,obj, 2);
		unk3 = ClassUtils.getFieldMember(Object.class,obj, 3);
		unk4 = ClassUtils.getFieldMember(Object.class,obj, 4);
		unk5 = ClassUtils.getFieldMember(Object.class,obj, 5);
		unk6 = ClassUtils.getFieldMember(Object.class,obj, 6);
		unk7 = ClassUtils.getFieldMember(Object.class,obj, 7);
		unk8 = ClassUtils.getFieldMember(Object.class,obj, 8);
		unk9 = ClassUtils.getFieldMember(Object.class,obj, 9);
		unk10 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 10);
		unk11 = ClassUtils.list(_1865.class,obj,11);
		unk12 = ClassUtils.getFieldMember(Object.class,obj, 12);
		unk13 = ClassUtils.list(java.lang.Long.class,obj,13);
		unk14 = ClassUtils.getFieldMember(Object.class,obj, 14);
		unk15 = ClassUtils.list(_1868.class,obj,15);
		unk16 = ClassUtils.getFieldMember(Object.class,obj, 16);
		unk17 = ClassUtils.getFieldMember(Object.class,obj, 17);
		unk18 = ClassUtils.getFieldMember(Object.class,obj, 18);
		unk19 = ClassUtils.getFieldMember(Object.class,obj, 19);
		unk20 = ClassUtils.getFieldMember(Object.class,obj, 20);
		unk21 = ClassUtils.list(_3230.class,obj,21);
		unk22 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 22);
		unk23 = ClassUtils.getFieldMember(Object.class,obj, 23);
		unk24 = ClassUtils.list(java.lang.Long.class,obj,24);
		unk25 = ClassUtils.list(java.lang.Long.class,obj,25);
		unk26 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 26);
		unk27 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 27);
		unk28 = ClassUtils.getFieldMember(Object.class,obj, 28);
		unk29 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 29);
		unk30 = ClassUtils.getFieldMember(Object.class,obj, 30);
		unk31 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 31);
		unk32 = ClassUtils.list(java.lang.Long.class,obj,32);
		unk33 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 33);
		unk34 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 34);
		unk35 = ClassUtils.getFieldMember(Object.class,obj, 35);
		unk36 = ClassUtils.getFieldMember(Object.class,obj, 36);
		unk37 = ClassUtils.getFieldMember(Object.class,obj, 37);
		unk38 = ClassUtils.getFieldMember(Object.class,obj, 38);
		unk39 = ClassUtils.getFieldMember(Object.class,obj, 39);
		unk40 = ClassUtils.list(java.lang.Long.class,obj,40);
		unk41 = ClassUtils.getFieldMember(Object.class,obj, 41);
		unk42 = ClassUtils.list(java.lang.Long.class,obj,42);
		unk43 = ClassUtils.getFieldMember(Object.class,obj, 43);
		unk44 = ClassUtils.getFieldMember(Object.class,obj, 44);
		unk45 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 45);
		unk46 = ClassUtils.list(java.lang.Long.class,obj,46);
		unk47 = ClassUtils.list(java.lang.Long.class,obj,47);
		unk48 = ClassUtils.getFieldMember(Object.class,obj, 48);
		unk49 = ClassUtils.getFieldMember(Object.class,obj, 49);
		unk50 = ClassUtils.getFieldMember(Object.class,obj, 50);
		unk51 = ClassUtils.getFieldMember(Object.class,obj, 51);
		unk52 = ClassUtils.getFieldMember(Object.class,obj, 52);
		unk53 = ClassUtils.getFieldMember(Object.class,obj, 53);
		unk54 = ClassUtils.getFieldMember(Object.class,obj, 54);
		unk55 = ClassUtils.getFieldMember(Object.class,obj, 55);
		unk56 = ClassUtils.getFieldMember(Object.class,obj, 56);
		unk57 = ClassUtils.getFieldMember(Object.class,obj, 57);
		unk58 = ClassUtils.getFieldMember(Object.class,obj, 58);
		unk59 = ClassUtils.getFieldMember(Object.class,obj, 59);
		unk60 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 60);
		unk61 = ClassUtils.getFieldMember(Object.class,obj, 61);
		unk62 = ClassUtils.list(java.lang.Long.class,obj,62);
		unk63 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 63);
		unk64 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 64);
		unk65 = ClassUtils.list(java.lang.Long.class,obj,65);
		unk66 = ClassUtils.getFieldMember(Object.class,obj, 66);
		unk67 = ClassUtils.getFieldMember(Object.class,obj, 67);
		unk68 = ClassUtils.getFieldMember(Object.class,obj, 68);
		unk69 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 69);
		unk70 = ClassUtils.getFieldMember(Object.class,obj, 70);
		unk71 = ClassUtils.getFieldMember(Object.class,obj, 71);
		unk72 = ClassUtils.getFieldMember(Object.class,obj, 72);
		unk73 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 73);
		unk74 = ClassUtils.list(java.lang.Long.class,obj,74);
		unk75 = ClassUtils.getFieldMember(Object.class,obj, 75);
		unk76 = ClassUtils.getFieldMember(Object.class,obj, 76);
		unk77 = ClassUtils.getFieldMember(Object.class,obj, 77);
		unk78 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 78);
		unk79 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 79);
		unk80 = ClassUtils.list(java.lang.Long.class,obj,80);
		unk81 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 81);
		unk82 = ClassUtils.getFieldMember(Object.class,obj, 82);
		unk83 = ClassUtils.getFieldMember(Object.class,obj, 83);
		unk84 = ClassUtils.getFieldMember(Object.class,obj, 84);
		unk85 = ClassUtils.list(java.lang.Long.class,obj,85);
		unk86 = ClassUtils.getFieldMember(Object.class,obj, 86);
		unk87 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 87);
	}
}
