package rift_extractor.classgen.classes;
import org.imathrowback.datparser.CObject;
import static rift_extractor.classgen.ClassUtils.*;
import rift_extractor.classgen.ClassUtils;

/** 3742 **/
@com.thoughtworks.xstream.annotations.XStreamAlias("_3742")
public class _3742 
{
	public _3742(){}
	public java.lang.Float unk0;
	public java.lang.Float unk1;
	public java.lang.Float unk2;
	public java.lang.Float unk3;
	Object unk4;
	Object unk5;
	Object unk6;
	Object unk7;
	public java.lang.Long unk8;
	Object unk9;
	Object unk10;
	Object unk11;
	Object unk12;
	Object unk13;
	Object unk14;
	public java.lang.Float unk15;
	public java.lang.Float unk16;
	Object unk17;
	Object unk18;
	Object unk19;
	Object unk20;
	public java.lang.Float unk21;
	public java.lang.Float unk22;
	public java.lang.Boolean unk23;
	Object unk24;
	Object unk25;
	public java.lang.Float unk26;
	public java.util.HashMap<java.lang.Long,_11332> unk27;
	Object unk28;
	public java.util.HashMap<java.lang.Long,_11339> unk29;
	public java.util.HashMap<java.lang.Long,_2401> unk30;
	public java.lang.Float unk31;
	Object unk32;
	public java.util.HashMap<java.lang.Long,_11334> unk33;
	Object unk34;
	public java.util.HashMap<java.lang.Long,_11315> unk35;
	public java.util.List<java.lang.Long> unk36;
	public java.lang.Float unk37;
	Object unk38;
	public java.lang.Float unk39;
	Object unk40;
	Object unk41;
	public java.lang.Float unk42;
	Object unk43;
	Object unk44;
	public java.lang.Float unk45;
	Object unk46;
	Object unk47;
	public java.lang.Float unk48;
	Object unk49;
	public java.lang.Float unk50;
	public java.lang.Float unk51;
	public java.lang.Float unk52;
	public java.lang.Float unk53;
	public java.lang.Float unk54;
	public java.lang.Float unk55;
	public java.lang.Float unk56;
	public java.lang.Float unk57;
	public java.lang.Float unk58;
	public java.lang.Float unk59;
	public java.lang.Float unk60;
	public java.lang.Float unk61;
	public java.lang.Float unk62;
	public java.lang.Float unk63;
	public java.lang.Float unk64;
	public java.lang.Float unk65;
	Object unk66;
	public java.util.HashMap<java.lang.Long,_2401> unk67;
	public java.util.HashMap<java.lang.Long,_2401> unk68;
	public java.util.HashMap<java.lang.Long,_2401> unk69;
	public java.util.HashMap<java.lang.Long,_2401> unk70;
	Object unk71;
	Object unk72;
	Object unk73;
	public java.util.HashMap<java.lang.Long,_11332> unk74;
	public java.util.HashMap<java.lang.Long,_11332> unk75;
	public java.util.HashMap<java.lang.Long,_11339> unk76;
	public java.lang.Long unk77;
	public java.lang.Long unk78;
	Object unk79;
	Object unk80;
	public java.lang.Float unk81;
	Object unk82;
	public java.util.List<java.lang.Long> unk83;
	public java.lang.Float unk84;
	Object unk85;
	public java.lang.Float unk86;
	public java.lang.Float unk87;
	public java.util.HashMap<java.lang.Long,_3163> unk88;
	Object unk89;
	Object unk90;
	Object unk91;
	Object unk92;
	Object unk93;
	public java.lang.Float unk94;
	public java.lang.Float unk95;
	public java.lang.Float unk96;
	public java.lang.Float unk97;
	public java.lang.Float unk98;
	public java.util.List<java.lang.Long> unk99;
	public java.lang.Float unk100;
	public java.lang.Boolean unk101;
	public java.lang.Long unk102;
	public java.lang.Long unk103;
	public java.lang.Long unk104;
	Object unk105;
	public java.lang.Long unk106;
	public java.lang.Float unk107;
	Object unk108;
	Object unk109;
	public java.lang.Float unk110;
	public java.lang.Float unk111;
	Object unk112;
	public java.lang.Long unk113;
	public java.lang.Long unk114;
	Object unk115;
	Object unk116;
	Object unk117;
	Object unk118;
	Object unk119;
	Object unk120;
	Object unk121;
	Object unk122;
	public java.lang.Float unk123;
	public java.lang.Long unk124;
	public java.lang.Long unk125;
	public java.lang.Float unk126;
	Object unk127;
	public java.util.List<_11331> unk128;
	public java.util.List<java.lang.Long> unk129;

	public void parse(CObject obj)
	{
		ClassUtils.assertType(obj, 3742);

		unk0 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 0);
		unk1 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 1);
		unk2 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 2);
		unk3 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 3);
		unk4 = ClassUtils.getFieldMember(Object.class,obj, 4);
		unk5 = ClassUtils.getFieldMember(Object.class,obj, 5);
		unk6 = ClassUtils.getFieldMember(Object.class,obj, 6);
		unk7 = ClassUtils.getFieldMember(Object.class,obj, 7);
		unk8 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 8);
		unk9 = ClassUtils.getFieldMember(Object.class,obj, 9);
		unk10 = ClassUtils.getFieldMember(Object.class,obj, 10);
		unk11 = ClassUtils.getFieldMember(Object.class,obj, 11);
		unk12 = ClassUtils.getFieldMember(Object.class,obj, 12);
		unk13 = ClassUtils.getFieldMember(Object.class,obj, 13);
		unk14 = ClassUtils.getFieldMember(Object.class,obj, 14);
		unk15 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 15);
		unk16 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 16);
		unk17 = ClassUtils.getFieldMember(Object.class,obj, 17);
		unk18 = ClassUtils.getFieldMember(Object.class,obj, 18);
		unk19 = ClassUtils.getFieldMember(Object.class,obj, 19);
		unk20 = ClassUtils.getFieldMember(Object.class,obj, 20);
		unk21 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 21);
		unk22 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 22);
		unk23 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 23);
		unk24 = ClassUtils.getFieldMember(Object.class,obj, 24);
		unk25 = ClassUtils.getFieldMember(Object.class,obj, 25);
		unk26 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 26);
		unk27 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 27);
		unk28 = ClassUtils.getFieldMember(Object.class,obj, 28);
		unk29 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 29);
		unk30 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 30);
		unk31 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 31);
		unk32 = ClassUtils.getFieldMember(Object.class,obj, 32);
		unk33 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 33);
		unk34 = ClassUtils.getFieldMember(Object.class,obj, 34);
		unk35 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 35);
		unk36 = ClassUtils.list(java.lang.Long.class,obj,36);
		unk37 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 37);
		unk38 = ClassUtils.getFieldMember(Object.class,obj, 38);
		unk39 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 39);
		unk40 = ClassUtils.getFieldMember(Object.class,obj, 40);
		unk41 = ClassUtils.getFieldMember(Object.class,obj, 41);
		unk42 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 42);
		unk43 = ClassUtils.getFieldMember(Object.class,obj, 43);
		unk44 = ClassUtils.getFieldMember(Object.class,obj, 44);
		unk45 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 45);
		unk46 = ClassUtils.getFieldMember(Object.class,obj, 46);
		unk47 = ClassUtils.getFieldMember(Object.class,obj, 47);
		unk48 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 48);
		unk49 = ClassUtils.getFieldMember(Object.class,obj, 49);
		unk50 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 50);
		unk51 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 51);
		unk52 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 52);
		unk53 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 53);
		unk54 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 54);
		unk55 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 55);
		unk56 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 56);
		unk57 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 57);
		unk58 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 58);
		unk59 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 59);
		unk60 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 60);
		unk61 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 61);
		unk62 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 62);
		unk63 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 63);
		unk64 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 64);
		unk65 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 65);
		unk66 = ClassUtils.getFieldMember(Object.class,obj, 66);
		unk67 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 67);
		unk68 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 68);
		unk69 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 69);
		unk70 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 70);
		unk71 = ClassUtils.getFieldMember(Object.class,obj, 71);
		unk72 = ClassUtils.getFieldMember(Object.class,obj, 72);
		unk73 = ClassUtils.getFieldMember(Object.class,obj, 73);
		unk74 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 74);
		unk75 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 75);
		unk76 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 76);
		unk77 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 77);
		unk78 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 78);
		unk79 = ClassUtils.getFieldMember(Object.class,obj, 79);
		unk80 = ClassUtils.getFieldMember(Object.class,obj, 80);
		unk81 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 81);
		unk82 = ClassUtils.getFieldMember(Object.class,obj, 82);
		unk83 = ClassUtils.list(java.lang.Long.class,obj,83);
		unk84 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 84);
		unk85 = ClassUtils.getFieldMember(Object.class,obj, 85);
		unk86 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 86);
		unk87 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 87);
		unk88 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 88);
		unk89 = ClassUtils.getFieldMember(Object.class,obj, 89);
		unk90 = ClassUtils.getFieldMember(Object.class,obj, 90);
		unk91 = ClassUtils.getFieldMember(Object.class,obj, 91);
		unk92 = ClassUtils.getFieldMember(Object.class,obj, 92);
		unk93 = ClassUtils.getFieldMember(Object.class,obj, 93);
		unk94 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 94);
		unk95 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 95);
		unk96 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 96);
		unk97 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 97);
		unk98 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 98);
		unk99 = ClassUtils.list(java.lang.Long.class,obj,99);
		unk100 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 100);
		unk101 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 101);
		unk102 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 102);
		unk103 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 103);
		unk104 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 104);
		unk105 = ClassUtils.getFieldMember(Object.class,obj, 105);
		unk106 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 106);
		unk107 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 107);
		unk108 = ClassUtils.getFieldMember(Object.class,obj, 108);
		unk109 = ClassUtils.getFieldMember(Object.class,obj, 109);
		unk110 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 110);
		unk111 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 111);
		unk112 = ClassUtils.getFieldMember(Object.class,obj, 112);
		unk113 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 113);
		unk114 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 114);
		unk115 = ClassUtils.getFieldMember(Object.class,obj, 115);
		unk116 = ClassUtils.getFieldMember(Object.class,obj, 116);
		unk117 = ClassUtils.getFieldMember(Object.class,obj, 117);
		unk118 = ClassUtils.getFieldMember(Object.class,obj, 118);
		unk119 = ClassUtils.getFieldMember(Object.class,obj, 119);
		unk120 = ClassUtils.getFieldMember(Object.class,obj, 120);
		unk121 = ClassUtils.getFieldMember(Object.class,obj, 121);
		unk122 = ClassUtils.getFieldMember(Object.class,obj, 122);
		unk123 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 123);
		unk124 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 124);
		unk125 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 125);
		unk126 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 126);
		unk127 = ClassUtils.getFieldMember(Object.class,obj, 127);
		unk128 = ClassUtils.list(_11331.class,obj,128);
		unk129 = ClassUtils.list(java.lang.Long.class,obj,129);
	}
}
