package rift_extractor.classgen.classes;
import org.imathrowback.datparser.CObject;
import static rift_extractor.classgen.ClassUtils.*;
import rift_extractor.classgen.ClassUtils;

/** 3751 **/
@com.thoughtworks.xstream.annotations.XStreamAlias("_3751")
public class _3751 
{
	public _3751(){}
	rift_extractor.classgen.Vector4 unk0;
	rift_extractor.classgen.Vector4 unk1;
	rift_extractor.classgen.Vector4 unk2;
	rift_extractor.classgen.Vector4 unk3;
	rift_extractor.classgen.Vector4 unk4;
	rift_extractor.classgen.Vector4 unk5;
	rift_extractor.classgen.Vector4 unk6;
	rift_extractor.classgen.Vector4 unk7;
	rift_extractor.classgen.Vector3 unk8;
	rift_extractor.classgen.Vector3 unk9;
	java.lang.Float unk10;
	rift_extractor.classgen.Vector3 unk11;
	rift_extractor.classgen.Vector3 unk12;
	java.lang.Float unk13;
	rift_extractor.classgen.Vector3 unk14;
	rift_extractor.classgen.Vector3 unk15;
	java.lang.Float unk16;
	rift_extractor.classgen.Vector3 unk17;
	rift_extractor.classgen.Vector3 unk18;
	java.lang.Float unk19;
	_3823 unk20;
	_3827 unk21;
	Object unk22;
	Object unk23;
	Object unk24;
	Object unk25;
	Object unk26;
	Object unk27;
	Object unk28;
	Object unk29;
	java.util.HashMap<java.lang.Long,_11316> unk30;
	java.lang.Long unk31;
	java.lang.Float unk32;
	java.lang.Float unk33;
	_3970 unk34;
	java.lang.Long unk35;
	_11524 unk36;
	Object unk37;
	Object unk38;
	java.lang.Float unk39;
	_3842 unk40;
	_3842 unk41;
	_3842 unk42;
	Object unk43;
	Object unk44;
	Object unk45;
	java.util.HashMap<java.lang.Long,_4322> unk46;
	java.lang.Float unk47;
	java.lang.Float unk48;
	java.util.List<java.lang.Long> unk49;
	java.lang.Float unk50;
	Object unk51;
	java.lang.Float unk52;
	java.lang.Float unk53;
	Object unk54;
	Object unk55;
	rift_extractor.classgen.Vector4 unk56;
	java.lang.Float unk57;
	java.lang.Float unk58;
	java.util.HashMap<java.lang.Long,_11316> unk59;
	Object unk60;
	java.util.List<_6012> unk61;
	java.util.List<java.lang.Long> unk62;
	java.util.List<_6012> unk63;
	java.util.List<_304> unk64;
	java.lang.Long unk65;
	java.lang.Long unk66;
	java.lang.Long unk67;
	java.lang.Long unk68;
	java.lang.Long unk69;
	java.lang.Long unk70;
	java.lang.Long unk71;
	java.lang.Long unk72;
	java.util.HashMap<java.lang.Long,_11316> unk73;
	java.util.HashMap<java.lang.Long,_11316> unk74;
	java.lang.Long unk75;
	java.lang.String unk76;
	java.lang.String unk77;
	java.lang.String unk78;
	java.lang.String unk79;
	java.lang.String unk80;
	java.lang.String unk81;
	java.lang.String unk82;
	java.lang.Boolean unk83;
	rift_extractor.classgen.Vector3 unk84;
	rift_extractor.classgen.Vector3 unk85;
	java.lang.Float unk86;
	java.lang.Float unk87;
	rift_extractor.classgen.Vector3 unk88;
	rift_extractor.classgen.Vector3 unk89;
	java.lang.Float unk90;
	java.lang.Float unk91;
	java.util.List<java.lang.Long> unk92;
	Object unk93;
	Object unk94;
	Object unk95;
	java.lang.Float unk96;
	java.lang.Float unk97;
	java.lang.Float unk98;
	_6017 unk99;
	java.lang.Float unk100;
	java.lang.Float unk101;
	java.lang.Boolean unk102;
	rift_extractor.classgen.Vector4 unk103;
	rift_extractor.classgen.Vector4 unk104;
	Object unk105;
	java.lang.Float unk106;
	java.util.List<java.lang.Long> unk107;
	java.lang.Float unk108;
	Object unk109;
	Object unk110;
	Object unk111;
	Object unk112;
	java.lang.Float unk113;
	Object unk114;
	java.lang.String unk115;
	java.lang.String unk116;
	java.lang.String unk117;
	java.lang.String unk118;
	java.lang.String unk119;
	Object unk120;
	Object unk121;
	Object unk122;
	Object unk123;
	Object unk124;
	Object unk125;
	Object unk126;
	java.util.List<_286> unk127;
	Object unk128;
	Object unk129;
	java.lang.Float unk130;
	Object unk131;
	Object unk132;
	Object unk133;
	Object unk134;
	Object unk135;
	java.util.HashMap<java.lang.Long,_1004> unk136;
	java.lang.Long unk137;
	java.util.List<java.lang.Long> unk138;

	public void parse(CObject obj)
	{
		ClassUtils.assertType(obj, 3751);

		unk0 = ClassUtils.vector4(obj,0);
		unk1 = ClassUtils.vector4(obj,1);
		unk2 = ClassUtils.vector4(obj,2);
		unk3 = ClassUtils.vector4(obj,3);
		unk4 = ClassUtils.vector4(obj,4);
		unk5 = ClassUtils.vector4(obj,5);
		unk6 = ClassUtils.vector4(obj,6);
		unk7 = ClassUtils.vector4(obj,7);
		unk8 = ClassUtils.vector3(obj,8);
		unk9 = ClassUtils.vector3(obj,9);
		unk10 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 10);
		unk11 = ClassUtils.vector3(obj,11);
		unk12 = ClassUtils.vector3(obj,12);
		unk13 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 13);
		unk14 = ClassUtils.vector3(obj,14);
		unk15 = ClassUtils.vector3(obj,15);
		unk16 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 16);
		unk17 = ClassUtils.vector3(obj,17);
		unk18 = ClassUtils.vector3(obj,18);
		unk19 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 19);
		unk20 = ClassUtils.getFieldMember(_3823.class,obj, 20);
		unk21 = ClassUtils.getFieldMember(_3827.class,obj, 21);
		unk22 = ClassUtils.getFieldMember(Object.class,obj, 22);
		unk23 = ClassUtils.getFieldMember(Object.class,obj, 23);
		unk24 = ClassUtils.getFieldMember(Object.class,obj, 24);
		unk25 = ClassUtils.getFieldMember(Object.class,obj, 25);
		unk26 = ClassUtils.getFieldMember(Object.class,obj, 26);
		unk27 = ClassUtils.getFieldMember(Object.class,obj, 27);
		unk28 = ClassUtils.getFieldMember(Object.class,obj, 28);
		unk29 = ClassUtils.getFieldMember(Object.class,obj, 29);
		unk30 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 30);
		unk31 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 31);
		unk32 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 32);
		unk33 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 33);
		unk34 = ClassUtils.getFieldMember(_3970.class,obj, 34);
		unk35 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 35);
		unk36 = ClassUtils.getFieldMember(_11524.class,obj, 36);
		unk37 = ClassUtils.getFieldMember(Object.class,obj, 37);
		unk38 = ClassUtils.getFieldMember(Object.class,obj, 38);
		unk39 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 39);
		unk40 = ClassUtils.getFieldMember(_3842.class,obj, 40);
		unk41 = ClassUtils.getFieldMember(_3842.class,obj, 41);
		unk42 = ClassUtils.getFieldMember(_3842.class,obj, 42);
		unk43 = ClassUtils.getFieldMember(Object.class,obj, 43);
		unk44 = ClassUtils.getFieldMember(Object.class,obj, 44);
		unk45 = ClassUtils.getFieldMember(Object.class,obj, 45);
		unk46 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 46);
		unk47 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 47);
		unk48 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 48);
		unk49 = ClassUtils.list(java.lang.Long.class,obj,49);
		unk50 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 50);
		unk51 = ClassUtils.getFieldMember(Object.class,obj, 51);
		unk52 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 52);
		unk53 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 53);
		unk54 = ClassUtils.getFieldMember(Object.class,obj, 54);
		unk55 = ClassUtils.getFieldMember(Object.class,obj, 55);
		unk56 = ClassUtils.vector4(obj,56);
		unk57 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 57);
		unk58 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 58);
		unk59 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 59);
		unk60 = ClassUtils.getFieldMember(Object.class,obj, 60);
		unk61 = ClassUtils.list(_6012.class,obj,61);
		unk62 = ClassUtils.list(java.lang.Long.class,obj,62);
		unk63 = ClassUtils.list(_6012.class,obj,63);
		unk64 = ClassUtils.list(_304.class,obj,64);
		unk65 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 65);
		unk66 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 66);
		unk67 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 67);
		unk68 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 68);
		unk69 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 69);
		unk70 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 70);
		unk71 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 71);
		unk72 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 72);
		unk73 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 73);
		unk74 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 74);
		unk75 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 75);
		unk76 = ClassUtils.getFieldMember(java.lang.String.class,obj, 76);
		unk77 = ClassUtils.getFieldMember(java.lang.String.class,obj, 77);
		unk78 = ClassUtils.getFieldMember(java.lang.String.class,obj, 78);
		unk79 = ClassUtils.getFieldMember(java.lang.String.class,obj, 79);
		unk80 = ClassUtils.getFieldMember(java.lang.String.class,obj, 80);
		unk81 = ClassUtils.getFieldMember(java.lang.String.class,obj, 81);
		unk82 = ClassUtils.getFieldMember(java.lang.String.class,obj, 82);
		unk83 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 83);
		unk84 = ClassUtils.vector3(obj,84);
		unk85 = ClassUtils.vector3(obj,85);
		unk86 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 86);
		unk87 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 87);
		unk88 = ClassUtils.vector3(obj,88);
		unk89 = ClassUtils.vector3(obj,89);
		unk90 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 90);
		unk91 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 91);
		unk92 = ClassUtils.list(java.lang.Long.class,obj,92);
		unk93 = ClassUtils.getFieldMember(Object.class,obj, 93);
		unk94 = ClassUtils.getFieldMember(Object.class,obj, 94);
		unk95 = ClassUtils.getFieldMember(Object.class,obj, 95);
		unk96 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 96);
		unk97 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 97);
		unk98 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 98);
		unk99 = ClassUtils.getFieldMember(_6017.class,obj, 99);
		unk100 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 100);
		unk101 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 101);
		unk102 = ClassUtils.getFieldMember(java.lang.Boolean.class,obj, 102);
		unk103 = ClassUtils.vector4(obj,103);
		unk104 = ClassUtils.vector4(obj,104);
		unk105 = ClassUtils.getFieldMember(Object.class,obj, 105);
		unk106 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 106);
		unk107 = ClassUtils.list(java.lang.Long.class,obj,107);
		unk108 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 108);
		unk109 = ClassUtils.getFieldMember(Object.class,obj, 109);
		unk110 = ClassUtils.getFieldMember(Object.class,obj, 110);
		unk111 = ClassUtils.getFieldMember(Object.class,obj, 111);
		unk112 = ClassUtils.getFieldMember(Object.class,obj, 112);
		unk113 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 113);
		unk114 = ClassUtils.getFieldMember(Object.class,obj, 114);
		unk115 = ClassUtils.getFieldMember(java.lang.String.class,obj, 115);
		unk116 = ClassUtils.getFieldMember(java.lang.String.class,obj, 116);
		unk117 = ClassUtils.getFieldMember(java.lang.String.class,obj, 117);
		unk118 = ClassUtils.getFieldMember(java.lang.String.class,obj, 118);
		unk119 = ClassUtils.getFieldMember(java.lang.String.class,obj, 119);
		unk120 = ClassUtils.getFieldMember(Object.class,obj, 120);
		unk121 = ClassUtils.getFieldMember(Object.class,obj, 121);
		unk122 = ClassUtils.getFieldMember(Object.class,obj, 122);
		unk123 = ClassUtils.getFieldMember(Object.class,obj, 123);
		unk124 = ClassUtils.getFieldMember(Object.class,obj, 124);
		unk125 = ClassUtils.getFieldMember(Object.class,obj, 125);
		unk126 = ClassUtils.getFieldMember(Object.class,obj, 126);
		unk127 = ClassUtils.list(_286.class,obj,127);
		unk128 = ClassUtils.getFieldMember(Object.class,obj, 128);
		unk129 = ClassUtils.getFieldMember(Object.class,obj, 129);
		unk130 = ClassUtils.getFieldMember(java.lang.Float.class,obj, 130);
		unk131 = ClassUtils.getFieldMember(Object.class,obj, 131);
		unk132 = ClassUtils.getFieldMember(Object.class,obj, 132);
		unk133 = ClassUtils.getFieldMember(Object.class,obj, 133);
		unk134 = ClassUtils.getFieldMember(Object.class,obj, 134);
		unk135 = ClassUtils.getFieldMember(Object.class,obj, 135);
		unk136 = ClassUtils.getFieldMember(java.util.HashMap.class,obj, 136);
		unk137 = ClassUtils.getFieldMember(java.lang.Long.class,obj, 137);
		unk138 = ClassUtils.list(java.lang.Long.class,obj,138);
	}
}
