package rift_extractor.classgen.classes;

import org.imathrowback.datparser.CObject;
import rift_extractor.classgen.ClassUtils;

/** 81 **/
@com.thoughtworks.xstream.annotations.XStreamAlias("_81")
public class _81
{
	public _81()
	{
	}

	Object unk0;
	java.lang.Long unk1;
	java.lang.Long unk2;
	java.lang.Float unk3;
	java.util.List<_1608> unk4;
	java.lang.Long unk5;
	Object unk6;
	java.util.List<java.lang.Long> unk7;
	java.lang.Long unk8;
	java.util.List<java.lang.Long> unk9;
	java.lang.Boolean unk10;
	java.util.List<java.lang.Long> unk11;
	java.lang.Long unk12;
	java.lang.Long unk13;
	java.util.List<_7721> unk14;
	java.lang.Long unk15;
	java.lang.Long unk16;
	java.lang.Long unk17;
	java.lang.Long unk18;
	java.lang.Long unk19;
	java.lang.Long unk20;
	java.lang.Float unk21;
	java.util.List<java.lang.Long> unk22;
	java.lang.Long unk23;
	java.lang.Long unk24;
	java.util.List<_1656> unk25;
	Object unk26;
	public TextEntry unk27;
	public TextEntry unk28;
	Object unk29;
	java.util.List<java.lang.Long> unk30;
	java.util.List<java.lang.Long> unk31;
	java.util.List<java.lang.Long> unk32;
	java.util.List<java.lang.Long> unk33;
	java.lang.Boolean unk34;
	java.lang.Boolean unk35;
	Object unk36;
	java.lang.Long unk37;
	java.util.List<_999539> unk38;
	public java.lang.Long unk39;
	java.lang.Boolean unk40;
	java.lang.Boolean unk41;
	java.lang.Long unk42;
	java.lang.Long unk43;
	java.lang.Boolean unk44;
	Object unk45;
	Object unk46;
	java.util.List<java.lang.Long> unk47;
	java.util.List<java.lang.Long> unk48;
	Object unk49;
	TextEntry unk50;
	java.lang.Boolean unk51;
	java.lang.Long unk52;
	java.lang.Float unk53;
	Object unk54;
	java.util.List<_1746> unk55;
	Object unk56;
	java.util.List<java.lang.Long> unk57;
	java.lang.Long unk58;
	TextEntry unk59;
	java.lang.Long unk60;
	java.lang.Float unk61;
	java.lang.Boolean unk62;
	java.util.List<_1877> unk63;
	Object unk64;
	Object unk65;
	java.lang.Long unk66;
	java.lang.Long unk67;
	Object unk68;
	TextEntry unk69;
	java.lang.Long unk70;
	Object unk71;
	Object unk72;
	java.lang.Long unk73;
	java.lang.Long unk74;
	java.lang.Boolean unk75;
	Object unk76;
	java.lang.Boolean unk77;
	java.lang.Boolean unk78;
	java.lang.String unk79;

	public void parse(final CObject obj)
	{
		ClassUtils.assertType(obj, 81);

		unk0 = ClassUtils.getFieldMember(Object.class, obj, 0);
		unk1 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 1);
		unk2 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 2);
		unk3 = ClassUtils.getFieldMember(java.lang.Float.class, obj, 3);
		unk4 = ClassUtils.list(_1608.class, obj, 4);
		unk5 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 5);
		unk6 = ClassUtils.getFieldMember(Object.class, obj, 6);
		unk7 = ClassUtils.list(java.lang.Long.class, obj, 7);
		unk8 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 8);
		unk9 = ClassUtils.list(java.lang.Long.class, obj, 9);
		unk10 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 10);
		unk11 = ClassUtils.list(java.lang.Long.class, obj, 11);
		unk12 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 12);
		unk13 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 13);
		unk14 = ClassUtils.list(_7721.class, obj, 14);
		unk15 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 15);
		unk16 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 16);
		unk17 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 17);
		unk18 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 18);
		unk19 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 19);
		unk20 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 20);
		unk21 = ClassUtils.getFieldMember(java.lang.Float.class, obj, 21);
		unk22 = ClassUtils.list(java.lang.Long.class, obj, 22);
		unk23 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 23);
		unk24 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 24);
		unk25 = ClassUtils.list(_1656.class, obj, 25);
		unk26 = ClassUtils.getFieldMember(Object.class, obj, 26);
		unk27 = ClassUtils.getFieldMember(TextEntry.class, obj, 27);
		unk28 = ClassUtils.getFieldMember(TextEntry.class, obj, 28);
		unk29 = ClassUtils.getFieldMember(Object.class, obj, 29);
		unk30 = ClassUtils.list(java.lang.Long.class, obj, 30);
		unk31 = ClassUtils.list(java.lang.Long.class, obj, 31);
		unk32 = ClassUtils.list(java.lang.Long.class, obj, 32);
		unk33 = ClassUtils.list(java.lang.Long.class, obj, 33);
		unk34 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 34);
		unk35 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 35);
		unk36 = ClassUtils.getFieldMember(Object.class, obj, 36);
		unk37 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 37);
		unk38 = ClassUtils.list(_999539.class, obj, 38);
		unk39 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 39);
		unk40 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 40);
		unk41 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 41);
		unk42 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 42);
		unk43 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 43);
		unk44 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 44);
		unk45 = ClassUtils.getFieldMember(Object.class, obj, 45);
		unk46 = ClassUtils.getFieldMember(Object.class, obj, 46);
		unk47 = ClassUtils.list(java.lang.Long.class, obj, 47);
		unk48 = ClassUtils.list(java.lang.Long.class, obj, 48);
		unk49 = ClassUtils.getFieldMember(Object.class, obj, 49);
		unk50 = ClassUtils.getFieldMember(TextEntry.class, obj, 50);
		unk51 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 51);
		unk52 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 52);
		unk53 = ClassUtils.getFieldMember(java.lang.Float.class, obj, 53);
		unk54 = ClassUtils.getFieldMember(Object.class, obj, 54);
		unk55 = ClassUtils.list(_1746.class, obj, 55);
		unk56 = ClassUtils.getFieldMember(Object.class, obj, 56);
		unk57 = ClassUtils.list(java.lang.Long.class, obj, 57);
		unk58 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 58);
		unk59 = ClassUtils.getFieldMember(TextEntry.class, obj, 59);
		unk60 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 60);
		unk61 = ClassUtils.getFieldMember(java.lang.Float.class, obj, 61);
		unk62 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 62);
		unk63 = ClassUtils.list(_1877.class, obj, 63);
		unk64 = ClassUtils.getFieldMember(Object.class, obj, 64);
		unk65 = ClassUtils.getFieldMember(Object.class, obj, 65);
		unk66 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 66);
		unk67 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 67);
		unk68 = ClassUtils.getFieldMember(Object.class, obj, 68);
		unk69 = ClassUtils.getFieldMember(TextEntry.class, obj, 69);
		unk70 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 70);
		unk71 = ClassUtils.getFieldMember(Object.class, obj, 71);
		unk72 = ClassUtils.getFieldMember(Object.class, obj, 72);
		unk73 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 73);
		unk74 = ClassUtils.getFieldMember(java.lang.Long.class, obj, 74);
		unk75 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 75);
		unk76 = ClassUtils.getFieldMember(Object.class, obj, 76);
		unk77 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 77);
		unk78 = ClassUtils.getFieldMember(java.lang.Boolean.class, obj, 78);
		unk79 = ClassUtils.getFieldMember(java.lang.String.class, obj, 79);
	}
}
